sudo: required

language: python

env:
  global:
    - secure: eV+M044ma2BRrnN3hnES6kjRrPcDkAfWn1pfCKWnPubTpPHcYUF9QhaP70DKuXvq8BWeh7vxG94na+HicPuicRKGsHA0/NFdL2gfQo3K2KNVYXujgFztKE1JqxvKJc6C9k9BPL9TkyjLe7ggVLDKOn3CkkNclh901N19AjqqWWLytlTh42eezsB96Wk0QXbYtZI94V1abGN9ACE/PlFtl+kLWzhWkAjmHl2eRu8oFOigBuBUajceiYmTaY/3aeRJ+S5Owl59EcVjxHASER3Z//853moCzZla6KlPvZjs98N9mVTgHEePKFatNuboDqwlw8E5VUWyhOVZOAEWs6QcrxH7axtO4WGMhvgl0eSo0N6FZiJBWD61LujC4Rco0GMcHLL9D/vzxIry1yvOVPopM0xLrvLgtGzrLFJfFHdxpLvPWcbmc6rzlsVxNlbCg1WMKXTmUY9AWy0sD8gKh4HW7rk4bNpg3lLkaEqUxIiFHy5xy4VY5dclXDT1nmP19I4mbgu/n2L6tgTje5LbTcI/kXaO8BN5A+D1MNDwLPA5NjHqW7sJrWlP8japZAPhpmMLKizpuBVb7M+PvqUkZlxtgwVBrhNtDyF22MkoNtXneMfRQU7Hfh+Xw3y3S5NWLF8rjRFHMdkml7+HZiIj7+Ll5BvkRsdynbUjsT36p2IOjOs=
    - secure: J1z6tVHmq+pidEaYfNUpwg8WBvAP/9atQBXJOL39OUGZD4trt6kejOLy7sW5HfZoJHTxKPSdVD5CYLaaRebPPbM1vXClHJE0u3l4rCpuMFuSQ/4J2env/st6P4cgcY4kPd9q9jqA7v3kDGBuoqDfXzKGMVm/zPyH36eUVlz9p/OhBeV9ZKtxAP9QdV0tOHiCfnkebLvHBsfvIKYud55Dpwq9bD6R5Tu+8lIjas/DfbWdA1kvYmtN2Uni4bchYEQnLD1s+USvEPj9UN5qNQhufT/0ZQVED8i5KqFndarb4t22tQNNei5kyOWvYjeaYpoIJVggHK3jL7MMHQmhsdtBXbCSD0D6NFGUzkVVMWZrzleMuowGXtHko6TWbPNIWaZrTiCcGYzCNJ7nUiuTNTDORjnpSC6/2JOXU8N1CXeOpKAWv+JkATvN1lJfhPLtq35XnpqOER/DF/OnNAlQDUzt5+m24OU6Hwl5/ylihiGoBclWzZkmxVhrAmxP+vuXDkVl8anYl/hszOhWzv9YotVGGPNn+faSysp7zgfEzf8oKgKIsDBAapSUzYH/sElnSK3NSv5sasLFReUIflcO7wtX5wuUEotbmfCfNoWWG4xIz3cocE2y5ytNsOW49cBPLBwdR3UqE2IqITDGaGGBZEkoa24MTCl+go3D189RkzrFIPo=
    - secure: MQUHf7F8AdVMm2ZwKPklQ/o5WfAT10CP05//pfGptmgkrNgZvlo00Lzar0Jj4aqyFNkJKuUiJzBazHozk9MY4vIo4gOUaIlPsLLJPl4Yl2n/7TeRy5BxyiJ/ZtoejYCWbWADqhuX/fN5HTh92f21slEZsshQouJctaUBajaI1RfThhACaFANDSYsFZk8ANla2W3kAUP9Ll8DOwnlgRsMCEKXIzj+4mugCDrRxFnGoo/9hgJQz1HI0ygqCnse89NmgUjoEosD0LJuLy755Uy01091h8FTW6Sm/Ly4EUr0fBB+4vCJXuy42yAB1Glw4JJlipEC9ApGJYe305GZYPIErhbL19Df9Sp+U1ffSJcOuBtJLvad/+YRDc69JfjUUuF0f1PV6n883cjwsbNSOWjUVXt3DEGuX72dh172ULZlXEAwGY3KvrW75L8RHoezNZiDK3DZgmEhXi0KYY/Zb89XGLmjLs3MWvV06Sn3mPiwGTeow7xkXMDToAaOjLTp6xPhinTSuqfKEi6xAQWaxHXqwT0O7D8DiCukkE4XCtZ48yKYHTJ6N9NR4MxFQl8pd2linDruU99JsU5FkRX2XyJvRW4PjgVMsgYH5XRlKweufUuiS6PpHQ9vsY/3YSpMtYRYpzO42UgVlmZckVJsvk0UMwiLYsm+zbAk9vpRf/2UIeE=

services:
  - docker

before_install:
  - pip install docker-compose
  - docker --version

script:
  - docker-compose -f docker-compose-build.yml build
  - docker-compose -f docker-compose-build.yml up -d
  - docker exec exemplofluxodocker_flapp_webapp_1 make test
  - docker run -it --net host --pid host --cap-add audit_control -v /var/lib:/var/lib -v /var/run/docker.sock:/var/run/docker.sock -v /usr/lib/systemd:/usr/lib/systemd -v /etc:/etc --label docker_bench_security docker/docker-bench-security

after_success:
  - docker login --email=$DOCKER_EMAIL --username=$DOCKER_USER --password=$DOCKER_PASS
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t $TRAVIS_REPO_SLUG .;
    docker push $TRAVIS_REPO_SLUG;
    fi
